import { mkdtemp, mkdir, readFile, rm, writeFile } from "node:fs/promises";
import { execFile } from "node:child_process";
import { tmpdir } from "node:os";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { promisify } from "node:util";

import * as esbuild from "esbuild";

const execFileAsync = promisify(execFile);

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const projectRoot = path.resolve(__dirname, "..");
const uiRoot = path.join(projectRoot, "worker", "ui");
const generatedDir = path.join(projectRoot, "worker", "generated");
const generatedModulePath = path.join(generatedDir, "selection_ui_bundle.js");

function tailwindBinaryPath() {
  return path.join(
    projectRoot,
    "node_modules",
    ".bin",
    process.platform === "win32" ? "tailwindcss.cmd" : "tailwindcss",
  );
}

async function buildCss(tempDir) {
  const outputPath = path.join(tempDir, "selection-app.css");
  await execFileAsync(tailwindBinaryPath(), [
    "--input",
    path.join(uiRoot, "styles.css"),
    "--output",
    outputPath,
    "--minify",
  ]);
  return readFile(outputPath, "utf8");
}

async function buildJs() {
  const result = await esbuild.build({
    entryPoints: [path.join(uiRoot, "selection-app.tsx")],
    bundle: true,
    write: false,
    format: "iife",
    platform: "browser",
    target: ["es2020"],
    jsx: "automatic",
    minify: true,
    logLevel: "silent",
    define: {
      "process.env.NODE_ENV": JSON.stringify("production"),
    },
  });

  const jsOutput = result.outputFiles.find((file) => file.path.endsWith(".js")) || result.outputFiles[0];
  if (!jsOutput) {
    throw new Error("Could not find the compiled UI JavaScript output.");
  }
  return jsOutput.text;
}

async function main() {
  const tempDir = await mkdtemp(path.join(tmpdir(), "agent-labbook-ui-"));
  try {
    const [cssText, jsText] = await Promise.all([buildCss(tempDir), buildJs()]);
    await mkdir(generatedDir, { recursive: true });
    await writeFile(
      generatedModulePath,
      [
        "// This file is generated by scripts/build_worker_ui.mjs.",
        `export const SELECTION_UI_CSS = ${JSON.stringify(cssText)};`,
        `export const SELECTION_UI_JS = ${JSON.stringify(jsText)};`,
        "",
      ].join("\n"),
      "utf8",
    );
  } finally {
    await rm(tempDir, { recursive: true, force: true });
  }
}

main().catch((error) => {
  console.error(error);
  process.exitCode = 1;
});
